### ISSUE TITLE
Installed headers incompatible with built library

### ISSUE THREAD

**Issue by ralisi** [siemens/libsecutils#47]
The system header `secutils/storage/uta_api.h` makes use of the compiler-time defined `SECUTILS_USE_UTA`.

As a result, this define must be supplied on every inclusion of this header, otherwise the headers used for compiling the library do not match the headers used later in development.

To my understanding, the installed headers should match the built binary. Cmake's `configure_file` could help here I think.

**Comment by DDvO** [comment]
Ping @ralisi

**Comment by ralisi** [comment]
I could not actually test it because too many changes have occurred in the meanwhile but looks good to me.
